bootstrapmvc/bootstrapmvc/Areas/ManagerPanel/Controllers/DashboardController.cs
using bootstrapmvc.Areas.ManagerPanel.Filters;
using bootstrapmvc.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace bootstrapmvc.Areas.ManagerPanel.Controllers
{
    [ManagerLoginRequiredFilter]
    public class DashboardController : Controller
    {
        Model1 db = new Model1();
        public ActionResult Index()
        {
            int toplam = db.Books.Count();
            int aktif = db.Books.Count(x => x.IsDeleted == false);
            int silinmis = db.Books.Count(x => x.IsDeleted == true);

            ViewBag.ToplamKitap = toplam;
            ViewBag.AktifKitap = aktif;
            ViewBag.SilinmisKitap = silinmis;

            List<Book> model = db.Books.ToList();

            return View(model);
        }
        public ActionResult _Index()
        {
            int toplamOgrenci = db.Students.Count();
            int aktifOgrenci = db.Students.Count(x => x.IsDeleted == false);
            int silinmisOgrenci = db.Students.Count(x => x.IsDeleted == true);

            ViewBag.ToplamOgrenci = toplamOgrenci;
            ViewBag.AktifOgrenci = aktifOgrenci;
            ViewBag.SilinmisOgrenci = silinmisOgrenci;

            List<Student> ogrenciler = db.Students.ToList();
            return View(ogrenciler);
        }
        public ActionResult BorrowStats()
        {
            DateTime today = DateTime.Today;

            int toplamOdunc = db.Borrows.Count();
            int teslimEdilen = db.Borrows.Count(x => x.IsReturned);
            int teslimEdilmeyen = db.Borrows.Count(x => !x.IsReturned);
            int gecikenler = db.Borrows.Count(b => !b.IsReturned && b.DueDate < today);

            ViewBag.ToplamOdunc = toplamOdunc;
            ViewBag.TeslimEdilen = teslimEdilen;
            ViewBag.TeslimEdilmeyen = teslimEdilmeyen;
            ViewBag.Geciken = gecikenler;

            List<Borrow> model = db.Borrows.Include("Student").Include("Book").ToList();

            return View(model);
        }
        public ActionResult BlackListStats(string searchName)
        {
            List<Borrow> allKaraListe = db.Borrows.Where(b => b.Penalty > 0).ToList();

            List<Borrow> karaListeQuery = db.Borrows.Where(b => b.Penalty > 0).Include(b => b.Student).Include(b => b.Book).ToList();

            if (!string.IsNullOrEmpty(searchName))
            {
                karaListeQuery = karaListeQuery.Where(b => b.Student.Name.Contains(searchName) || b.Student.Surname.Contains(searchName)).ToList();
            }

            List<Borrow> karaListe = karaListeQuery;

            ViewBag.KaraListeOgrenciSayisi = allKaraListe.Select(b => b.StudentID).Distinct().Count();
            ViewBag.ToplamCezaTutari = allKaraListe.Sum(b => b.Penalty);

            if (!string.IsNullOrEmpty(searchName))
            {
                ViewBag.FiltreliCezaTutari = karaListe.Sum(b => b.Penalty);
            }
            else
            {
                ViewBag.FiltreliCezaTutari = 0;
            }

            ViewBag.SearchName = searchName;

            return View(karaListe);

           /*var allKaraListe = db.Borrows.Where(b => b.Penalty > 0).ToList();

            var karaListeQuery = db.Borrows.Where(b => b.Penalty > 0);

            if (!string.IsNullOrEmpty(searchName))
            {
                karaListeQuery = karaListeQuery.Where(b => b.Student.Name.Contains(searchName) || b.Student.Surname.Contains(searchName));
            }

            var karaListe = karaListeQuery.Include(b => b.Student).Include(b => b.Book).ToList();

            ViewBag.KaraListeOgrenciSayisi = allKaraListe.Select(b => b.StudentID).Distinct().Count();
            ViewBag.ToplamCezaTutari = allKaraListe.Sum(b => b.Penalty);

            if (!string.IsNullOrEmpty(searchName))
            {
                ViewBag.FiltreliCezaTutari = karaListeQuery.Sum(b => (decimal?)b.Penalty) ?? 0;
            }
            else
            {
                ViewBag.FiltreliCezaTutari = 0;
            }

            ViewBag.SearchName = searchName;

            return View(karaListe); */


        }


    }

    
}

bootstrapmvc/bootstrapmvc/Areas/ManagerPanel/Controllers/LoginController.cs
using bootstrapmvc.Areas.ManagerPanel.Data;
using bootstrapmvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace bootstrapmvc.Areas.ManagerPanel.Controllers
{
    public class LoginController : Controller
    {
        Model1 db= new Model1();
        public ActionResult Index()
        {
            if (Request.Cookies["ManagerCookie"] != null)
            {
                HttpCookie SavedCookie = Request.Cookies["ManagerCookie"];
                string mail = SavedCookie.Values["mail"];
                string password = SavedCookie.Values["password"];

                Manager m = db.Managers.FirstOrDefault(x => x.Mail == mail && x.Password == password);
                if (m != null)
                {
                    if (m.IsActive)
                    {
                        Session["ManagerSession"] = m;
                        return RedirectToAction("Index", "Home");
                    }
                }
            }
            return View(new ManagerLoginViewModel());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(ManagerLoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                Manager m = db.Managers.FirstOrDefault(x => x.Mail == model.Mail && x.Password == model.Password);
                if (m != null)
                {
                    if (m.IsActive)
                    {
                        if (model.RememberMe)
                        {
                            HttpCookie cookie = new HttpCookie("ManagerCookie");
                            cookie["mail"] = model.Mail;
                            cookie["password"] = model.Password;
                            cookie.Expires = DateTime.Now.AddDays(10);
                            Response.Cookies.Add(cookie);
                        }
                        Session["ManagerSession"] = m;
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        ViewBag.mesaj = "Kullanıcı hesabınız askıya alınmıştır";
                    }
                }
                else
                {
                    ViewBag.mesaj = "Kullanıcı bulunamadı";
                }
            }
            return View(model);
        }
        public ActionResult LogOut()
        {
            Session["ManagerSession"] = null;
            if (Request.Cookies["ManagerCookie"] != null)
            {
                HttpCookie SavedCookie = Request.Cookies["ManagerCookie"];
                SavedCookie.Expires = DateTime.Now.AddDays(-1);
                Response.Cookies.Add(SavedCookie);
            }

            return RedirectToAction("Index", "Default");
        }
    }
}

bootstrapmvc/bootstrapmvc/Areas/ManagerPanel/Views/Shared/_LayoutPage1.cshtml
@using bootstrapmvc.Models;
@{
    Manager m = new Manager();
    if (Session["ManagerSession"] != null)
    {
        m = Session["ManagerSession"] as Manager;
    }

    string badgeClass = "bg-secondary";
    string iconClass = "fa-solid fa-user";

    switch (m.managerRole.Name)
    {
        case "Admin":
            badgeClass = "bg-primary";
            iconClass = "fa-solid fa-crown";
            break;
        case "Moderatör":
            badgeClass = "bg-primary";
            iconClass = "fa-solid fa-shield-halved"; 
            break;
    }
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
    <link href="~/Scripts/fontawesome-free-6.7.2-web/fontawesome-free-6.7.2-web/css/all.min.css" rel="stylesheet" />
    @RenderSection("styles", false)
</head>
<body>
    <div class="alert alert-primary">
        <strong><i class="fa-solid fa-user"></i> Hoşgeldin @m.Name</strong>
        <div class="float-end">
            <span class="badge @badgeClass me-2">
                <i class="@iconClass"></i> @m.managerRole.Name
            </span>
            <a href="@Url.Action("LogOut", "Login")"
               class="btn btn-outline-dark btn-sm"
               onclick="return confirm('Çıkış yapmak istediğinize emin misiniz?');">
                <i class="fa-solid fa-right-from-bracket"></i> Çıkış Yap
            </a>
        </div>
    </div>
    <div class="container mt-3">
        <ul class="nav">
            <li class="nav-item">
                <a href="@Url.Action("Index", "Home")" class="nav-link">
                    <i class="fa-solid fa-house"></i> Anasayfa
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link" data-bs-toggle="offcanvas" data-bs-target="#dashboard" aria-controls="dashboard">
                    <i class="fa-solid fa-chart-line"></i> Dashboard
                </a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("Index", "Book")" class="nav-link">
                    <i class="fa-solid fa-book"></i> Kitap Listesi
                </a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("Index", "Student")" class="nav-link">
                    <i class="fa-solid fa-user-graduate"></i> Öğrenciler
                </a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("Index", "Borrow")" class="nav-link">
                    <i class="fa-solid fa-book-reader"></i> Ödünç İşlemleri
                </a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("Index", "BlackList")" class="nav-link">
                    <i class="fa-solid fa-skull"></i> Kara Liste
                </a>
            </li>
        </ul>
        <div class="offcanvas offcanvas-end text-bg-dark" id="dashboard" data-bs-backdrop="true">
            <div class="offcanvas-header">
                <h3 class="offcanvas-title">İstatistikler</h3>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Kapat"></button>
            </div>
            <div class="offcanvas-body">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a href="@Url.Action("Index", "Dashboard")" class="nav-link">
                            <i class="fa-solid fa-book"></i> Kitaplar
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("_Index", "Dashboard")" class="nav-link">
                            <i class="fa-solid fa-user-graduate"></i> Öğrenciler
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("BorrowStats", "Dashboard")" class="nav-link">
                            <i class="fa-solid fa-book-open-reader"></i> Ödünçler
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("BlackListStats", "Dashboard")" class="nav-link">
                            <i class="fa-solid fa-skull"></i> Kara Liste
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container mt-4">
        @RenderBody()
    </div>
    @RenderSection("scripts", false)
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
</body>
</html>